global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape app running from IDE (dev mode)
  - job_name: 'twitter-app-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s

  # Scrape app instances in Docker (prod mode)
  - job_name: 'twitter-app-docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['twitter-app-prod:8080']
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
